export const GET_ORDERS_BY_RESTAURANTS = "GET_ORDERS_BY_RESTAURANTS";
export const GET_ALL_ORDERS_BY_RESTAURANTS = "GET_ALL_ORDERS_BY_RESTAURANTS";
export const GET_ALL_ORDERS_ALL_RESTAURANTS = "GET_ALL_ORDERS_ALL_RESTAURANTS";
export const ADD_COMMISION = "ADD_COMMISION";
export const UPDATE_COMMISION= "UPDATE_COMMISION";
export const GET_COMMISION= "GET_COMMISION";
export const GET_REVIEWS= "GET_REVIEWS";
export const GET_ALL_ORDERS= "GET_ALL_ORDERS";
export const DATA_LOADING= "DATA_LOADING";
export const ADD_LIVREUR="ADD_LIVREUR";
export const GET_LIVREUR="GET_LIVREUR";
export const ALL_ORDERS= "ALL_ORDERS";
export const UPDATE_ORDERS= "UPDATE_ORDERS";
export const ADD_MOSTPOPULAR= "ADD_MOSTPOPULAR";
export const DELETE_MOSTPOPULAR= "DELETE_MOSTPOPULAR";
export const GET_MOSTPOPULAR= "GET_MOSTPOPULAR";
export const ADD_TRENDING= "ADD_TRENDING";
export const DELETE_TRENDING= "DELETE_TRENDING";
export const GET_TRENDING= "GET_TRENDING";
export const GET_PROMOTIONS= "GET_PROMOTIONS";
export const ADD_PROMOTIONS= "ADD_PROMOTIONS";
export const DELETE_PROMOTIONS= "DELETE_PROMOTIONS";
export const ALL_NOTIFICATIONS="ALL_NOTIFICATIONS";
export const ETAT_VUE="ETAT_VUE";
export const AFFECT_ORDER="AFFECT_ORDER"

//restaurants action
export const GET_NEW_RESTAURANTS= "GET_NEW_RESTAURANTS";
export const GET_BANNE_RESTAURANTS= "GET_BANNE_RESTAURANTS";
export const GET_ALL_RESTAURANTS= "GET_ALL_RESTAURANTS";
export const ACTIVATE_RESTAURANT= "ACTIVATE_RESTAURANT";
export const BANNE_RESTAURANT= "BANNE_RESTAURANT";
export const UNBANNE_RESTAURANT= "UNBANNE_RESTAURANT";
export const GET_ARGENTS_RESTAURANTS= "GET_ARGENTS_RESTAURANTS";

